/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-31 10:49:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/index_header.jsp", Long.valueOf(1577413294000L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/index_footer.jsp", Long.valueOf(1577413278000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar", Long.valueOf(1575813510165L));
    _jspx_dependants.put("jar:file:/C:/SpringSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team_Y_final/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528824936000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\">\n");
      out.write("<meta name=\"author\" content=\"Kyusup\">\n");
      out.write("<meta name=\"description\" content=\"반응형 웹 도서관 사이트\">\n");
      out.write("<meta name=\"keywords\" content=\"반응형사이트, 웹퍼블리셔, 웹접근성, HTML5\">\n");
      out.write("<title>도서관 프로젝트</title>\n");
      out.write("\n");
      out.write("<!-- style -->\n");
      out.write("<link href=\"../resources/html/css/reset.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/style.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/font-awesome.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/slick.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/lightgallery.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/border.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- 파비콘 -->\n");
      out.write("<!--\n");
      out.write("  <link rel=\"shortcut icon\" href=\"icon/favicon.ico\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" href=\"icon/favicon-152.png\">\n");
      out.write("  <link rel=\"icon\" href=\"path/to/favicon.png\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-16.png\" sizes=\"16x16\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-32.png\" sizes=\"32x32\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-48.png\" sizes=\"48x48\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-64.png\" sizes=\"64x64\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-128.png\" sizes=\"128x128\">\n");
      out.write("-->\n");
      out.write("<!-- 웹 폰트 -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Brush+Script\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Abel\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- HTLM5shiv ie6~8 -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("        <script src=\"resources/html/js/html5shiv.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            alert(\"현재 당신이 보는 브라우저는 지원하지 않습니다. 최신 브라우저로 업데이트해주세요!\");\n");
      out.write("        </script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("<!-- 교재 속 css -->\n");
      out.write("<!-- Bootstrap Core CSS -->\n");
      out.write("<link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- MetisMenu CSS -->\n");
      out.write("<link href=\"/resources/vendor/metisMenu/metisMenu.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- DataTables CSS -->\n");
      out.write("<link\n");
      out.write("\thref=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- DataTables Responsive CSS -->\n");
      out.write("<link\n");
      out.write("\thref=\"/resources/vendor/datatables-responsive/dataTables.responsive.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom Fonts -->\n");
      out.write("<link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t\t<div class=\"header_menu\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t<select name=\"language\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ko\">한국어</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"en\">English</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- //header_menu -->\n");
      out.write("\t\t\t\t\t<div class=\"header_tit\">\n");
      out.write("\t\t\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"search\" /> <input type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"location.href = '/boardList'\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--                   <button type=\"submit\" onclick=\"location.href='/bookList'\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!--                   \t<i class=\"fa fa-search\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!--                   \t</i> -->\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- //header_tit -->\n");
      out.write("\t\t\t\t\t<!--          <div class=\"header_icon\">\n");
      out.write("            <ul>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-html5\" aria-hidden=\"true\"></i><span>HTML5</span></a></li>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-github\" aria-hidden=\"true\"></i><span>GitHub</span></a></li>\n");
      out.write("              <li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook-square\" aria-hidden=\"true\"></i><span>Fackbook</span></a></li>\n");
      out.write("              <li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i><span>twitter</span></a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>1\n");
      out.write("-->\n");
      out.write("\t\t\t\t\t<!-- //header_icon -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- //nav -->\n");
      out.write("\n");
      out.write("\t<nav id=\"nav\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"nav\">\n");
      out.write("\t\t\t\t\t<h2 class=\"ir_su\">전체 메뉴</h2>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>도서관 소개</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 소개</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 시설</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 이용 안내</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">찾아오시는 길</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>도서 관리</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/boardList\">소장 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">예약 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/wish/guide\">희망 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">추천 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>열람실 관리</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">열람실 예약</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>공지사항</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>게시판</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/forum/list\">자유 게시판</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t<!-- //nav -->\n");
      out.write("\n");
      out.write("\t<article id=\"title\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"title\">\n");
      out.write("\t\t\t\t<h2>list</h2>\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn\"> <i class=\"fa fa-angle-down\"\n");
      out.write("\t\t\t\t\taria-hidden=\"true\"></i> <span class=\"ir_su\">전체메뉴 보기</span>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</article>\n");
      out.write("\t<!-- //title -->\n");
      out.write("\t\n");
      out.write("\t<!-- main -->\n");
      out.write("\t<section id=\"contents\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h2 class=\"ir_su\">반응형 사이트 컨텐츠</h2>\n");
      out.write("\t\t\t<section id=\"cont_left\">\n");
      out.write("\t\t\t\t<h3 class=\"ir_su\">메뉴 및 게시판 컨텐츠 영역</h3>\n");
      out.write("\t\t\t\t<article class=\"column col1\">\n");
      out.write("\t\t\t\t\t<h4 class=\"col_tit\">Menu</h4>\n");
      out.write("\t\t\t\t\t<p class=\"col_desc\">이 곳은 메뉴 영역입니다.</p>\n");
      out.write("\t\t\t\t\t<!-- 메뉴 -->\n");
      out.write("\t\t\t\t\t<div class=\"menu\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 소개 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/boardList\">소장 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">예약 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/wish/guide\">희망 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">추천 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">열람실 관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항 <i class=\"fa fa-angle-double-right\"\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/forum/list\">자유 게시판 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--//메뉴 -->\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\t\t\t\t<!-- //col1 -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t\t<section id=\"cont_center\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".admin_page{\r\n");
      out.write("\tborder : 1px solid black;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:600px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".admin_page tr, td{\r\n");
      out.write("\twidth:17%;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t<table class='admin_page'>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><a href=#>회원관리</a></td>\r\n");
      out.write("\t\t\t<td><a href=#>Q&A</a></td>\r\n");
      out.write("\t\t\t<td><a href=#>도서등록</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><a href='/wish/wishlist_state'>희망도서관리</a></td>\r\n");
      out.write("\t\t\t<td><a href=#>게시글관리</a></td>\r\n");
      out.write("\t\t\t<td><a href=#>공지사항관리</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 도움말</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 운영원칙</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><strong>개인정보취급방침</strong></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">책임의 한계와 법적고지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">게시중단요청서비스</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\tCopyright &copy;<strong>중앙 501 A조</strong> All Rights Reserved.\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<!--   <script src=\"../resources/html/js/jquery.min_1.12.4.js\"></script> -->\r\n");
      out.write("<script src=\"../resources/html/js/modernizr-custom.js\"></script>\r\n");
      out.write("<script src=\"../resources/html/js/slick.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/html/js/lightgallery.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/html/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--   <!-- 교재 속 css  -->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Metis Menu Plugin JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     DataTables JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Custom Theme JavaScript -->\r\n");
      out.write("<script src=\"/resources/dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Page-Level Demo Scripts - Tables - Use for reference -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/admin/../includes/index_header.jsp(94,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_sec_005fauthorize_005f1(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t<a href=\"/mypage/myinfo\">마이페이지</a>\n");
        out.write("\t\t\t\t\t\t<a href=\"/customLogout\">로그아웃</a>\n");
        out.write("\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/admin/../includes/index_header.jsp(95,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("hasRole('ROLE_ADMIN')");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(" \n");
        out.write("\t\t\t\t\t\t\t\t<a href=\"/admin/main\">관리자페이지</a>\n");
        out.write("\t\t\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/admin/../includes/index_header.jsp(101,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t\t<a href=\"/customLogin\">\n");
        out.write("\t\t\t\t\t\t\t\t로그인</a><a href=\"#\">회원가입</a>\n");
        out.write("\t\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }
}
