/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-31 09:38:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.forum;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/forum/../includes/index_header.jsp", Long.valueOf(1577413294000L));
    _jspx_dependants.put("/WEB-INF/views/forum/../includes/index_footer.jsp", Long.valueOf(1577413278000L));
    _jspx_dependants.put("jar:file:/C:/SpringSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team_Y_final/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar", Long.valueOf(1575813510165L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1575813496543L));
    _jspx_dependants.put("jar:file:/C:/SpringSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team_Y_final/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528824936000L));
    _jspx_dependants.put("jar:file:/C:/SpringSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team_Y_final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\">\n");
      out.write("<meta name=\"author\" content=\"Kyusup\">\n");
      out.write("<meta name=\"description\" content=\"반응형 웹 도서관 사이트\">\n");
      out.write("<meta name=\"keywords\" content=\"반응형사이트, 웹퍼블리셔, 웹접근성, HTML5\">\n");
      out.write("<title>도서관 프로젝트</title>\n");
      out.write("\n");
      out.write("<!-- style -->\n");
      out.write("<link href=\"../resources/html/css/reset.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/style.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/font-awesome.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/slick.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/lightgallery.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link href=\"../resources/html/css/border.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- 파비콘 -->\n");
      out.write("<!--\n");
      out.write("  <link rel=\"shortcut icon\" href=\"icon/favicon.ico\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" href=\"icon/favicon-152.png\">\n");
      out.write("  <link rel=\"icon\" href=\"path/to/favicon.png\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-16.png\" sizes=\"16x16\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-32.png\" sizes=\"32x32\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-48.png\" sizes=\"48x48\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-64.png\" sizes=\"64x64\">\n");
      out.write("  <link rel=\"icon\" href=\"icon/favicon-128.png\" sizes=\"128x128\">\n");
      out.write("-->\n");
      out.write("<!-- 웹 폰트 -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Brush+Script\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Abel\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- HTLM5shiv ie6~8 -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("        <script src=\"resources/html/js/html5shiv.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            alert(\"현재 당신이 보는 브라우저는 지원하지 않습니다. 최신 브라우저로 업데이트해주세요!\");\n");
      out.write("        </script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("<!-- 교재 속 css -->\n");
      out.write("<!-- Bootstrap Core CSS -->\n");
      out.write("<link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- MetisMenu CSS -->\n");
      out.write("<link href=\"/resources/vendor/metisMenu/metisMenu.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- DataTables CSS -->\n");
      out.write("<link\n");
      out.write("\thref=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- DataTables Responsive CSS -->\n");
      out.write("<link\n");
      out.write("\thref=\"/resources/vendor/datatables-responsive/dataTables.responsive.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom Fonts -->\n");
      out.write("<link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t\t<div class=\"header_menu\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t<select name=\"language\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ko\">한국어</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"en\">English</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- //header_menu -->\n");
      out.write("\t\t\t\t\t<div class=\"header_tit\">\n");
      out.write("\t\t\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"search\" /> <input type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"location.href = '/boardList'\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--                   <button type=\"submit\" onclick=\"location.href='/bookList'\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!--                   \t<i class=\"fa fa-search\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!--                   \t</i> -->\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- //header_tit -->\n");
      out.write("\t\t\t\t\t<!--          <div class=\"header_icon\">\n");
      out.write("            <ul>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-html5\" aria-hidden=\"true\"></i><span>HTML5</span></a></li>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-github\" aria-hidden=\"true\"></i><span>GitHub</span></a></li>\n");
      out.write("              <li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook-square\" aria-hidden=\"true\"></i><span>Fackbook</span></a></li>\n");
      out.write("              <li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i><span>twitter</span></a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>1\n");
      out.write("-->\n");
      out.write("\t\t\t\t\t<!-- //header_icon -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- //nav -->\n");
      out.write("\n");
      out.write("\t<nav id=\"nav\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"nav\">\n");
      out.write("\t\t\t\t\t<h2 class=\"ir_su\">전체 메뉴</h2>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>도서관 소개</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 소개</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 시설</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 이용 안내</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">찾아오시는 길</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>도서 관리</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/boardList\">소장 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">예약 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/wish/guide\">희망 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">추천 도서 관리</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>열람실 관리</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">열람실 예약</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>공지사항</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<h3>게시판</h3>\n");
      out.write("\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/forum/list\">자유 게시판</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판</a></li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t<!-- //nav -->\n");
      out.write("\n");
      out.write("\t<article id=\"title\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"title\">\n");
      out.write("\t\t\t\t<h2>list</h2>\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn\"> <i class=\"fa fa-angle-down\"\n");
      out.write("\t\t\t\t\taria-hidden=\"true\"></i> <span class=\"ir_su\">전체메뉴 보기</span>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</article>\n");
      out.write("\t<!-- //title -->\n");
      out.write("\t\n");
      out.write("\t<!-- main -->\n");
      out.write("\t<section id=\"contents\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h2 class=\"ir_su\">반응형 사이트 컨텐츠</h2>\n");
      out.write("\t\t\t<section id=\"cont_left\">\n");
      out.write("\t\t\t\t<h3 class=\"ir_su\">메뉴 및 게시판 컨텐츠 영역</h3>\n");
      out.write("\t\t\t\t<article class=\"column col1\">\n");
      out.write("\t\t\t\t\t<h4 class=\"col_tit\">Menu</h4>\n");
      out.write("\t\t\t\t\t<p class=\"col_desc\">이 곳은 메뉴 영역입니다.</p>\n");
      out.write("\t\t\t\t\t<!-- 메뉴 -->\n");
      out.write("\t\t\t\t\t<div class=\"menu\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">도서관 소개 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/boardList\">소장 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">예약 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/wish/guide\">희망 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">추천 도서관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">열람실 관리 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항 <i class=\"fa fa-angle-double-right\"\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/forum/list\">자유 게시판 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Q&A 게시판 <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--//메뉴 -->\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\t\t\t\t<!-- //col1 -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t\t<section id=\"cont_center\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".yun_btn{\r\n");
      out.write("\t width:75px;\r\n");
      out.write("\t height:30px;\r\n");
      out.write("\t padding:0;\r\n");
      out.write("\t margin-right:5px;\r\n");
      out.write("/* \t display: inline-block; */\r\n");
      out.write("/* \t position: absolute; */\r\n");
      out.write("/* \t margin-right:5px; */\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<h1 class=\"page-header\">자유게시판</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.col-lg-12 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.row -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">게시글 등록</div>\r\n");
      out.write("\t\t\t<!-- /.panel-heading -->\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<form role=\"form\" action=\"/forum/register\" method=\"post\" id='register'>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"bcategory\" value=\"자유게시판\"/>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>카테고리</label> <select name=\"pcategory\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"독서토론\">독서토론</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"스터디\">스터디</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"기타\">기타</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>제목</label> <input class=\"form-control\" name=\"title\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>내용</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"3\" name=\"tbl_contents\" placeholder=\"규정을 위반한 게시물은 경고 및 삭제 조치 될 수 있습니다.\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>작성자</label> <input class=\"form-control\" name=\"user_id\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\treadonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default yun_btn\">등록</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"reset\" class=\"btn btn-default yun_btn\">다시 작성</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.panel-body -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.panel -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.col-lg-6 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">File Attach</div>\r\n");
      out.write("<!-- \t\t\t/.panel-heading  -->\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group uploadDiv\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" name=\"uploadFile\" multiple>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='uploadResult'>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- \t\t\tend panel-body -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- \t\tend panel-body -->\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- \tend panel -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(e) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar csrfHeaderName = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar csrfTokenValue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".uploadResult\").on(\"click\",\"button\",function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"delete file\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar targetFile = $(this).data(\"file\");\r\n");
      out.write("\t\t\t\tvar type = $(this).data(\"type\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar targetLi = $(this).closest(\"li\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({url : '/deleteFile',\r\n");
      out.write("\t\t\t\t\t\tdata : {fileName : targetFile, type : type},\r\n");
      out.write("\t\t\t\t\t\tbeforeSend : function(xhr) {xhr.setRequestHeader(csrfHeaderName,csrfTokenValue);},\r\n");
      out.write("\t\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talert(result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttargetLi.remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});//$.ajax\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar formObj = $(\"form[role='form']\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"button[type='submit']\").on(\"click\",function(e) {\r\n");
      out.write("\t\t\t\t\t\tif(!formObj.find(\"input[name='title']\").val()){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(!formObj.find(\"textarea[name='tbl_contents']\").val()){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"내용을 입력하세요\");\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"submit clicked\");\r\n");
      out.write("\t\t\t\t\t\tvar str = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\".uploadResult ul li\").each(function(i, obj) {//i는 인덱스번호\r\n");
      out.write("\t\t\t\t\t\t\t\tvar jobj = $(obj);\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.dir(jobj);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//게시물 등록시 이미 업로드된 첨부파일들을 내부적으로 input태그로 만들어 form 태그가 submit될 때 같이 전송되도록 함\r\n");
      out.write("\t\t\t\t\t\tstr += \"<input type='hidden' name='attachList[\"\r\n");
      out.write("\t\t\t\t\t\t\t+ i+ \"].fileName' value='\"\r\n");
      out.write("\t\t\t\t\t\t\t+ jobj.data(\"filename\")+ \"'>\";\r\n");
      out.write("\t\t\t\t\t\tstr += \"<input type='hidden' name='attachList[\"\r\n");
      out.write("\t\t\t\t\t\t\t+ i+ \"].uuid' value='\"+ jobj.data(\"uuid\")+ \"'>\";\r\n");
      out.write("\t\t\t\t\t\tstr += \"<input type='hidden' name='attachList[\"\r\n");
      out.write("\t\t\t\t\t\t\t+ i+ \"].uploadPath' value='\"+ jobj.data(\"path\")+ \"'>\";\r\n");
      out.write("\t\t\t\t\t\tstr += \"<input type='hidden' name='attachList[\"\r\n");
      out.write("\t\t\t\t\t\t\t+ i+ \"].fileType' value='\"+ jobj.data(\"type\")+ \"'>\";\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tformObj.append(str).submit();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar regex = new RegExp(\"(.*?)\\.(exe|sh|zip|alz)$\");\r\n");
      out.write("\t\t\t\t\t\tvar maxSize = 5242880;//5MB\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfunction checkExtension(fileName, fileSize) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (fileSize >= maxSize) {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"파일 사이즈 초과\");\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif (regex.test(fileName)) {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"해당 종류의 파일은 업로드할 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\treturn true;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\"input[type='file']\").change(function(e) {\r\n");
      out.write("\t\t\t\t\t\t\tvar formData = new FormData();\r\n");
      out.write("\t\t\t\t\t\t\tvar inputFile = $(\"input[name='uploadFile']\");\r\n");
      out.write("\t\t\t\t\t\t\tvar files = inputFile[0].files;\r\n");
      out.write("\t\t\t\t\t\t\tfor (var i = 0; i < files.length; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (!checkExtension(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfiles[i].name,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfiles[i].size)) {//확장자와 파일크기 체크\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tformData.append(\"uploadFile\",files[i]);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : '/uploadAjaxAction',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbeforeSend : function(xhr) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\txhr.setRequestHeader(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcsrfHeaderName,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcsrfTokenValue);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata : formData, //ajax를 통해 formData 자체를 전송\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tshowUploadResult(result); //업로드 결과 처리 함수\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}); //$.ajax\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfunction showUploadResult(uploadResultArr) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (!uploadResultArr || uploadResultArr.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar uploadUL = $(\".uploadResult ul\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar str = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(uploadResultArr).each(function(i, obj) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t//image type check\r\n");
      out.write("\t\t\t\t\t\t\t\tif (!obj.image) { //이미지가 아니면 첨부파일 이미지 붙이기 \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar fileCallPath = encodeURIComponent(obj.uploadPath\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ obj.uuid\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ obj.fileName);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar fileLink = fileCallPath\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.replace(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew RegExp(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t/\\\\/g),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"/\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//var regExp = /정규표현식/[Flag]; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//Flag g:global- 문자열의 모든 패턴을 찾음\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//Flag i:Ignore Case - 문자열의 대소문자구분x\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//Flag m:Multi line -문자열의 행이 바뀌어도 찾음\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<li \";\r\n");
      out.write("\t\t\t\t\tstr+=\"data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"\r\n");
      out.write("\t\t\t\t\t\t\t+obj.fileName+\"'data-type='\"+obj.image+\"'><div>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<span>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ obj.fileName\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</span>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<button type='button' data-file=\\'\"\r\n");
      out.write("\t\t\t\t\t\t\t+fileCallPath+\"\\' data-type='file' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<img src='/resources/img/attach.png'></a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"</div></li>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar fileCallPath = encodeURIComponent(obj.uploadPath\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"/s_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ obj.uuid\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ obj.fileName);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<li \";\r\n");
      out.write("\t\t\t\t\tstr+=\"data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"\r\n");
      out.write("\t\t\t\t\t\t\t+obj.fileName+\"'data-type='\"+obj.image+\"'><div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<span>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ obj.fileName\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</span>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' \";\r\n");
      out.write("\t\t\t\t\tstr+=\"data-type='image' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<img src='/display?fileName=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ fileCallPath\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"</div></li>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tuploadUL.append(str);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".uploadResult {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-flow: row;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul li {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\talign-content: center;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul li img {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul li span {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigPictureWrapper {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\ttop: 0%;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigPicture {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigPicture img {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 도움말</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 운영원칙</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><strong>개인정보취급방침</strong></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">책임의 한계와 법적고지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">게시중단요청서비스</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\tCopyright &copy;<strong>중앙 501 A조</strong> All Rights Reserved.\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<!--   <script src=\"../resources/html/js/jquery.min_1.12.4.js\"></script> -->\r\n");
      out.write("<script src=\"../resources/html/js/modernizr-custom.js\"></script>\r\n");
      out.write("<script src=\"../resources/html/js/slick.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/html/js/lightgallery.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/html/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--   <!-- 교재 속 css  -->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Metis Menu Plugin JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     DataTables JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Custom Theme JavaScript -->\r\n");
      out.write("<script src=\"/resources/dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Page-Level Demo Scripts - Tables - Use for reference -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/forum/../includes/index_header.jsp(94,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_sec_005fauthorize_005f1(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t<a href=\"/mypage/myinfo\">마이페이지</a>\n");
        out.write("\t\t\t\t\t\t<a href=\"/customLogout\">로그아웃</a>\n");
        out.write("\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/forum/../includes/index_header.jsp(95,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("hasRole('ROLE_ADMIN')");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(" \n");
        out.write("\t\t\t\t\t\t\t\t<a href=\"/admin/main\">관리자페이지</a>\n");
        out.write("\t\t\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/forum/../includes/index_header.jsp(101,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t\t<a href=\"/customLogin\">\n");
        out.write("\t\t\t\t\t\t\t\t로그인</a><a href=\"#\">회원가입</a>\n");
        out.write("\t\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/forum/register.jsp(55,14) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.username");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }
}
