/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-22 06:13:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1575813496543L));
    _jspx_dependants.put("jar:file:/C:/SpringSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_mybatis/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\">\r\n");
      out.write("  <meta name=\"author\" content=\"Kyusup\">\r\n");
      out.write("  <meta name=\"description\" content=\"반응형 웹 도서관 사이트\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"반응형사이트, 웹퍼블리셔, 웹접근성, HTML5\">\r\n");
      out.write("  <title>도서관 프로젝트</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- style -->\r\n");
      out.write("  <link href=\"resources/html/css/reset.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/html/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/html/css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/html/css/slick.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/html/css/lightgallery.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/html/css/border.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- 웹 폰트 -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Nanum+Brush+Script\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Abel\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- HTLM5shiv ie6~8 -->\r\n");
      out.write("  <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"resources/html/js/html5shiv.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            alert(\"현재 당신이 보는 브라우저는 지원하지 않습니다. 최신 브라우저로 업데이트해주세요!\");\r\n");
      out.write("        </script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <header id=\"header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("          <div class=\"header_menu\">\r\n");
      out.write("            <a href=\"resources/html/form/loginForm.html\">로그인</a>\r\n");
      out.write("            <a href=\"#\">회원가입</a>\r\n");
      out.write("            <select name = \"language\">\r\n");
      out.write("              <option value=\"ko\">한국어</option>\r\n");
      out.write("              <option value=\"en\">English</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- //header_menu -->\r\n");
      out.write("          <div class=\"header_tit\">\r\n");
      out.write("            <form>\r\n");
      out.write("              <fieldset>\r\n");
      out.write("                <input type=\"search\"/>\r\n");
      out.write("\t\t\t\t<input type = \"button\" onclick = \"location.href = '/boardList'\"/>\r\n");
      out.write("              </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- //nav -->\r\n");
      out.write("\r\n");
      out.write("  <nav id=\"nav\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("          <h2 class=\"ir_su\">전체 메뉴</h2>\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3>도서관 소개</h3>\r\n");
      out.write("            <ol>\r\n");
      out.write("              <li><a href=\"#\">도서관 소개</a></li>\r\n");
      out.write("              <li><a href=\"#\">도서관 시설</a></li>\r\n");
      out.write("              <li><a href=\"#\">도서관 이용 안내</a></li>\r\n");
      out.write("              <li><a href=\"#\">찾아오시는 길</a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3>도서 관리</h3>\r\n");
      out.write("            <ol>\r\n");
      out.write("              <li><a href=\"/boardList\">소장 도서 관리</a></li>\r\n");
      out.write("              <li><a href=\"#\">예약 도서 관리</a></li>\r\n");
      out.write("              <li><a href=\"#\">희망 도서 관리</a></li>\r\n");
      out.write("              <li><a href=\"#\">추천 도서 관리</a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3>열람실 관리</h3>\r\n");
      out.write("            <ol>\r\n");
      out.write("              <li><a href=\"#\">열람실 예약</a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3>공지사항</h3>\r\n");
      out.write("            <ol>\r\n");
      out.write("              <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3>게시판</h3>\r\n");
      out.write("            <ol>\r\n");
      out.write("              <li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("              <li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- //nav -->\r\n");
      out.write("\r\n");
      out.write("  <article id=\"title\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <h2>list</h2>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("       \t\t<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("        \t<span class=\"ir_su\">전체메뉴 보기</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <!-- //title -->\r\n");
      out.write("\r\n");
      out.write("  <!-- main -->\r\n");
      out.write("    <section id=\"contents\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2 class=\"ir_su\">반응형 사이트 컨텐츠</h2>\r\n");
      out.write("        <section id=\"cont_left\">\r\n");
      out.write("          <h3 class=\"ir_su\">메뉴 및 게시판 컨텐츠 영역</h3>\r\n");
      out.write("          <article class=\"column col1\">\r\n");
      out.write("            <h4 class=\"col_tit\">Menu</h4>\r\n");
      out.write("            <p class=\"col_desc\">이 곳은 메뉴 영역입니다.</p>\r\n");
      out.write("            <!-- 메뉴 -->\r\n");
      out.write("            <div class=\"menu\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"#\">도서관 소개 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"/boardList\">소장 도서관리 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("               \t<li><a href=\"#\">예약 도서관리 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\">희망 도서관리 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\">추천 도서관리 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("              \t<li><a href=\"#\">열람실 관리 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\">공지사항 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\">자유 게시판 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\">Q&A 게시판 <i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--//메뉴 -->\r\n");
      out.write("          </article>\r\n");
      out.write("          <!-- //col1 -->\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- //cont_left -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- cont_center -->\r\n");
      out.write("\t\t<section id = \"cont_center\">\r\n");
      out.write("\t\t<div class=\"boardcss_list_table\">\r\n");
      out.write("\t\t\t<h2>소장도서 관리</h2>\r\n");
      out.write("\t\t\t<table class = \"list_table\">\r\n");
      out.write("\t\t\t\t<caption>소장도서 관리</caption>\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>도서번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>분류기호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>도서명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>출판사</th>\r\n");
      out.write("\t\t\t\t\t\t<th>발행일</th>\r\n");
      out.write("\t\t\t\t\t\t<th>ISBN</th>\r\n");
      out.write("\t\t\t\t\t\t<th>부록여부</th>\r\n");
      out.write("\t\t\t\t\t\t<th>예약여부</th>\r\n");
      out.write("\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- //contents -->\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">사이트 도움말</a></li>\r\n");
      out.write("            <li><a href=\"#\">사이트 이용약관</a></li>\r\n");
      out.write("            <li><a href=\"#\">사이트 운영원칙</a></li>\r\n");
      out.write("            <li><a href=\"#\"><strong>개인정보취급방침</strong></a></li>\r\n");
      out.write("            <li><a href=\"#\">책임의 한계와 법적고지</a></li>\r\n");
      out.write("            <li><a href=\"#\">게시중단요청서비스</a></li>\r\n");
      out.write("            <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <address>\r\n");
      out.write("            Copyright &copy;<strong>중앙 501 A조</strong> All Rights Reserved.\r\n");
      out.write("          </address>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("  <!-- JavaScript Libraries -->\r\n");
      out.write("  <script src=\"resources/html/js/jquery.min_1.12.4.js\"></script>\r\n");
      out.write("  <script src=\"resources/html/js/modernizr-custom.js\"></script>\r\n");
      out.write("  <script src=\"resources/html/js/slick.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/html/js/lightgallery.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/html/js/script.js\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/boardList.jsp(179,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("book");
      // /WEB-INF/views/boardList.jsp(179,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/boardList.jsp(179,5) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.sign}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.publisher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.redate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.ISBN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.sup_check}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.reserve}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.views}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
